### ISSUE TITLE
Convert this boilerplate to react with javascript es6 - not an issue - help wanted

### ISSUE THREAD

**Issue by Samesh** [digital-wonderland/play-webpack-typescript-react#1]
Hi,
Could you help me configure this to work with JavaScript instead of Typescript. I'm new to webpack and have been trying to configure this for some time now.
What loaders do I need to add to webpack and which ones do I need to remove? Thanks

**Comment by mnm364** [comment]
Bump. @Samesh were you able to figure this out? I am trying to do the same thing. If/When I get it working I'll be sure to give you a hand. Thanks so much for your time.

**Comment by mnm364** [comment]
@Samesh, see the PR into this repo or see my fork (https://github.com/mnm364/play-webpack-typescript-react). Good luck with all.

**Comment by digital-wonderland** [comment]
@mnm364 's changes are now available in the ```javascript``` branch.
