### ISSUE TITLE
(not an issue) How did you deploy this?

### ISSUE THREAD

**Issue by cnguy** [digital-wonderland/play-webpack-typescript-react#4]
Hi, this is more of a noob question -- sorry to disturb you. I was wondering how you deployed this starter project?

**Comment by digital-wonderland** [comment]
The same way you would deploy any other Play project.

As in on your CI server or local machine ```npm``` must be installed. Then, when you run sbt's ```dist``` target, sbt will not only build your scala code but also run webpack to build your frontend.

The result will be included in the built artifact, so you can deploy it however you normally deploy any play applications.
